kind: Deployment
apiVersion: apps/v1
metadata:
  name: vaultwarden
  labels:
    app: vaultwarden
    part-of: vaultwarden
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@hourly"
    keel.sh/match-tag: true
    keel.sh/approvals: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
      part-of: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
        part-of: vaultwarden
    spec:
      serviceAccountName: vaultwarden
      containers:
      - name: vaultwarden
        image: vaultwarden/server:latest
        ports:
        - name: vaultwarden
          containerPort: 80
        env:
        - name: DOMAIN
          valueFrom:
            secretKeyRef:
              name: vaultwarden
              key: DOMAIN
        - name: ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: vaultwarden
              key: ADMIN_TOKEN
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: vaultwarden
              key: SMTP_HOST
        - name: SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: vaultwarden
              key: SMTP_PORT
        - name: SMTP_FROM
          valueFrom:
            secretKeyRef:
              name: vaultwarden
              key: SMTP_FROM
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: vaultwarden
              key: SMTP_USERNAME
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vaultwarden
              key: SMTP_PASSWORD
        - name: SIGNUPS_ALLOWED
          value: "false"
        - name: SHOW_PASSWORD_HINT
          value: "false"
        readinessProbe:
          httpGet:
            path: /
            port: vaultwarden
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: vaultwarden
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          limits:
            memory: 64Mi
          requests:
            memory: 32Mi
        volumeMounts:
        - name: vaultwarden
          mountPath: /data
        - name: vaultwarden-secrets
          mountPath: "/mnt/vault"
          readOnly: true
      volumes:
      - name: vaultwarden
        persistentVolumeClaim:
          claimName: vaultwarden
      - name: vaultwarden-secrets
        csi:
          driver: "secrets-store.csi.k8s.io"
          readOnly: true
          volumeAttributes:
            secretProviderClass: "vaultwarden"
