---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vaultwarden
  annotations:
    nfs.io/storage-path: "data01/vaultwarden"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
